export { default as CardSideBar } from './CardSideBar.vue'
export { default as HeaderPart } from './HeaderPart.vue'
export { default as Navbar } from './NavBar.vue'
export { default as MobileMenu } from './MobileMenu.vue'
export { default as NewsLetter } from './NewsLetter.vue'
export { default as FooterPart } from './FooterPart.vue'
